name = "Create + Addons"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d0c3007bcf9c18d708b8bcd4836014e3d2aa6d05a9192820ca620a585d66b2e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
