name = "Create + Addons"
author = "Nicoladen"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6c5affeb82ecd3b07b85cdc616351c7101cc29c72d623f74858e01ce1e62911"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
