name = "Create + Addons"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f7ab8a5835e980ae8ee81ef1fdf321d58df25eaddae7ec4064af2a35ee07223"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
