name = "Create + Addons"
author = "Nicoladen"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d584b87804304373450a7a570bf1e5b7c1950d4e43f3bec0fdc7d6f163d04f44"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
