name = "Create + Addons"
author = "Nicoladen"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da582f4f19b9a2bff3bfe4178874501703e872b1b2a380a311bc4f0d155c272c"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
