name = "Create + Addons"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "039067482c7001378e06f2a8fbb5e9dbacc648fb786fcbd2d1867705a51129d2"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
