name = "Create + Addons"
author = "Nicoladen"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c48336c0763b3d311054eb786173e13a4f9cc04c30c3d9a1b937590980fb1c38"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
