name = "Create + Addons"
author = "Nicoladen"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61a9b30781cc318efedb54cef3864b285e7f1c4fb8ca0332a52c6d04a5ff81c0"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
