name = "Create + Addons"
author = "Nicoladen"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5da6c011f998af46cbc775ba99f5702b3770e8caa136f2a01d0f8ba06fbef536"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
